- manifests/service.pp
- metadata.json
- spec/classes/ferm_spec.rb
> Add official ubuntu support

- .github/CONTRIBUTING.md
- .msync.yml
- .travis.yml
- Gemfile
> modulesync 2.0.0

- metadata.json
> allow puppet 6.x and  puppetlabs/concat 5.x

- CHANGELOG.md
- metadata.json
> release 1.3.2

- .github/CONTRIBUTING.md
- .msync.yml
- Gemfile
> modulesync 2.1.0

- CHANGELOG.md
- metadata.json
> release 1.4.0

- .github/CONTRIBUTING.md
- .travis.yml
- Dockerfile
- Gemfile
- Rakefile
> modulesync 2.5.1

- .msync.yml
> modulesync 2.6.0

- CHANGELOG.md
- REFERENCE.md
- metadata.json
> Release 2.2.0

- README.md
- REFERENCE.md
- manifests/chain.pp
- manifests/rule.pp
- spec/defines/rule_spec.rb
> add support for interface specific rules

- REFERENCE.md
- types/chains.pp
- types/policies.pp
- types/protocols.pp
> allow all supported iptables protocolls & enhance puppet-strings documentation Unverified

- REFERENCE.md
- data/Debian-10.yaml
- data/common.yaml
- manifests/chain.pp
- manifests/config.pp
- manifests/init.pp
- manifests/rule.pp
- metadata.json
- spec/classes/ferm_spec.rb
- spec/defines/chain_spec.rb
- spec/defines/rule_spec.rb
- templates/ferm.conf.epp
- templates/ferm_header.conf.epp
- types/chains.pp
> Add Debian 10 support & make configdirectory configureable

- REFERENCE.md
- data/common.yaml
- manifests/config.pp
- manifests/init.pp
- spec/classes/ferm_spec.rb
- templates/ferm.conf.epp
> allow preserving of chains in tables

- metadata.json
> drop Debian from supported OSes

- files/ferm
> add missing status option for CentOS 6 init script

- README.md
- REFERENCE.md
- manifests/rule.pp
> enhance puppet-strings documentation

- CHANGELOG.md
- metadata.json
> release 2.5.0

- REFERENCE.md
- manifests/init.pp
> update docker firewalling example

- README.md
- REFERENCE.md
- manifests/chain.pp
- manifests/ipset.pp
- spec/defines/ipset_spec.rb
- templates/ferm-chain-ipset.epp
> implement ipset support

- manifests/ipset.pp
> ipset: allow multiple instances of defined resource

- CHANGELOG.md
- metadata.json
> release 2.6.0

- .github/CONTRIBUTING.md
- .msync.yml
- .rubocop.yml
- Gemfile
- Rakefile
- spec/spec_helper.rb
> modulesync 3.0.0

- metadata.json
> Add VZ 6/7 to metadata.json

- REFERENCE.md
- manifests/chain.pp
- manifests/config.pp
- manifests/init.pp
- manifests/install.pp
- manifests/ipset.pp
- manifests/service.pp
> cleanup puppet-strings documentation

- REFERENCE.md
- manifests/chain.pp
- manifests/config.pp
- manifests/init.pp
- spec/acceptance/ferm_spec.rb
- templates/ferm_chain_header.conf.epp
> make dropping of invalid pakets optional

- REFERENCE.md
- manifests/chain.pp
> by default dont log dropped packets

- .github/SECURITY.md
- .msync.yml
- .rubocop.yml
- Gemfile
- manifests/config.pp
- manifests/init.pp
- manifests/install.pp
- manifests/ipset.pp
- manifests/rule.pp
- manifests/service.pp
> modulesync 3.0.0 & puppet-lint updates

- metadata.json
> Drop Puppet 5; enable Puppet 7 support

- .github/CONTRIBUTING.md
- .github/workflows/ci.yml
- .github/workflows/release.yml
- .msync.yml
- Dockerfile
- Gemfile
- spec/type_aliases/actions_spec.rb
- spec/type_aliases/policies_spec.rb
- spec/type_aliases/port_spec.rb
- spec/type_aliases/protocols_spec.rb
- spec/type_aliases/tables_spec.rb
> modulesync 4.1.0

- .fixtures.yml
- spec/classes/ferm_spec.rb
> enhance spec coverage

- Gemfile
> puppetlabs_spec_helper: Allow 3.x

- REFERENCE.md
- manifests/init.pp
- manifests/install.pp
- spec/classes/ferm_spec.rb
> Enable users to the package ensure

- CHANGELOG.md
- REFERENCE.md
- metadata.json
> release 6.0.0

- README.md
- REFERENCE.md
- manifests/rule.pp
- spec/defines/rule_spec.rb
> delete legacy `policy` param in ferm::rule

- metadata.json
> allow latest dependencies

- .msync.yml
- Gemfile
- spec/acceptance/ferm_spec.rb
- spec/classes/ferm_spec.rb
- spec/defines/chain_spec.rb
- spec/defines/ipset_spec.rb
- spec/defines/rule_spec.rb
- spec/spec_helper.rb
- spec/spec_helper_acceptance.rb
- spec/type_aliases/actions_spec.rb
- spec/type_aliases/policies_spec.rb
- spec/type_aliases/port_spec.rb
- spec/type_aliases/protocols_spec.rb
- spec/type_aliases/tables_spec.rb
> modulesync 5.0.0

- manifests/install.pp
- spec/classes/ferm_spec.rb
> Packages: Install packages before ferm install

- manifests/init.pp
- manifests/install.pp
- spec/classes/ferm_spec.rb
Add parameter `manage_package` to enable managing ferm package outside of this module
> Add parameter `manage_package` to enable managing ferm package outside of this module

- manifests/init.pp
> ferm vcs install: Update 2.5.1->2.6

- CHANGELOG.md
- REFERENCE.md
- metadata.json
> Release 8.0.0

- .fixtures.yml
- .msync.yml
- Gemfile
- Rakefile
- spec/spec_helper.rb
> modulesync 5.4.0

- CHANGELOG.md
- REFERENCE.md
- metadata.json
> release 8.1.0

- metadata.json
> drop EOL OSes Debian-9 and Ubuntu-16.04

- spec/type_aliases/negation_spec.rb
Add missing test for `Ferm::Negation`
> add test for 'Ferm::Negation'

- metadata.json
- spec/acceptance/ferm_spec.rb
> Add Debian 11 support

- metadata.json
Ref: https://github.com/voxpupuli/community-triage/issues/44
> puppetlabs/vcsrepo Allow 7.x
