manifests/rule.pp
this comes from the stdlib: https://github.com/puppetlabs/puppetlabs-stdlib#squeeze
=> use squeeze() to remove duplicate whitespace

data/common.yaml, manifests/chain.pp, manifests/config.pp, manifests/init.pp, spec/defines/chain_spec.rb, templates/ferm_chain_header.conf.epp
Default value of 'disable_conntrack' is 'false'. Existing installations are not affected by this change.
=> introduce parameter disable_conntrack

README.md, manifests/rule.pp
Adding `proto_options` covers use cases which require more protocol info than just `tcp`, `udp`, or `icmp`. The following example will suppress the hostname in programs like `traceroute`:
```yaml
---
ferm::rules:
'drop_output_traceroute':
chain: 'OUTPUT'
policy: 'DROP'
proto: 'icmp'
proto_options: 'icmp-type time-exceeded'
```
=> Add `proto_options` to enable usage of icmp types

REFERENCE.md, data/common.yaml, manifests/config.pp, manifests/init.pp, templates/ferm.conf.epp
The current version, by default, set up rules for iptables v4 and v6 and it is impossible to modify this.
On host with only one version enabled, the service fail during start.
The PR add a new parameter that permits to choose the version we want to use.
=> permit to choose ipv4, ipv6 or both

README.md, data/common.yaml, files/ferm, manifests/init.pp, manifests/install.pp, spec/classes/ferm_spec.rb
OS like CentOS 6 are missing an init script for ferm. This PR ...
- adds an init script inspired by Kellermann's script for Debian and
- adds a test for RedHat-like OS to contain this init script
=> Add RedHat init script

README.md, manifests/rule.pp, spec/defines/rule_spec.rb
Adds data type `Array` to `ferm::rule` for `saddr` and `daddr`. This makes configuration of subnets in Hiera more maintainable:
- before
- _either_
``` 
subnet01: '123.123.123.0/24'
subnet02: '123.123.124.0/24'
subnet03: '123.123.125.0/24'
subnets: "%{hiera('subnet01')} ${hiera('subnet02')} %{hiera('subnet03')}"
```
- _or_
```
subnets: '123.123.123.0/24 123.123.124.0/24 123.123.125.0/24 123.123.126.0/24 123.123.127.0/24 ...`
```
- changing anything in those strings isn't very diff-friendly
- now
```
subnet01: '123.123.123.0/24'
subnet02: '123.123.124.0/24'
subnet03: '123.123.125.0/24'
subnets:
- %{hiera('subnet01')} 
- %{hiera('subnet02')}
- %{hiera('subnet03')}
- 123.123.126.0/24 
- 123.123.127.0/24 
```
todo:
=> Allow array for saddr and daddr

metadata.json
This module only works on systems with a linux kernel and iptables.
=> remove FreeBSD from supported OS list

REFERENCE.md, manifests/chain.pp, manifests/config.pp, manifests/init.pp, manifests/rule.pp, spec/acceptance/ferm_spec.rb, spec/classes/ferm_spec.rb, spec/defines/chain_spec.rb, spec/defines/rule_spec.rb, spec/spec_helper.rb, templates/ferm-table-chain-config-include.epp, templates/ferm.conf.epp, templates/ferm_chain_header.conf.epp, templates/ferm_header.conf.epp, types/actions.pp, types/policies.pp, types/tables.pp
Currently rules can only be configured in the `filter` table of ferm/iptables.
For some scenarios it can be required to configure rules in the `nat`, `mangle` or `raw` tables as certain operations can only be done is these tables respectively.
For reference see:
https://stuffphilwrites.com/wp-content/uploads/2016/11/FW-IDS-iptables-Flowchart-2016-11-18.png
This PR is intended to implement the missing functionality.
- allow configuring rules in other tables than `filter`
- allow defining custom chains and jump to them (#61)
```
Total resources:   83
Touched resources: 83
Resource coverage: 100.00%
895 examples, 0 failures
```
=> add ability to configure rules in tables other than the default "filter" table

REFERENCE.md, manifests/chain.pp, manifests/config.pp, spec/classes/ferm_spec.rb
Certain kernel modules and thus iptables functionality was introduced at
later releases, so we need to properly reflect that in our default chain
initialization procedure.
`INPUT` chain for `nat` table was introduced with 2.6.36
`ip6table_nat` kernel module for NAT functionality with IPv6 was
introduced with 3.17
This commit implements the required conditional constraints and includes
the rspec tests to validate it.
=> fix kernel incompatibilities

manifests/config.pp, spec/acceptance/ferm_spec.rb
conntrack filtering basically doesn't work in those chains, so we need
to disable it.
=> disable conntrack filtering in FORWARD/OUTPUT

manifests/config.pp, spec/acceptance/ferm_spec.rb
The PR #81 disable conntrack on `OUTPUT`.
With `output_policy` to `DROP` value, upgrading to `puppet-ferm` 2.6.0 block network access to nodes.
This change was not backward compatible.
* step 1 release a 2.7.0 without breaking change. Because upgrading from 2.x to last 2.x is expected to break nothing
* step 2 release a 3.0.0 with PR81 re added.
=> revert PR81

REFERENCE.md, manifests/chain.pp, manifests/config.pp, manifests/init.pp, spec/acceptance/ferm_spec.rb
This tries to reintroduce what was done in #81 in a way more customizable. This  
permits to have default policy to DROP with OUTPUT chain.
=> use dedicated conntrack parameters / by default disable conntrack for new chains /  by default enable conntrack for filter INPUT chain

.travis.yml
without this, the travis linter tells us the following warning:
```
root: missing os, using the default linux
```
=> Add missing os key in travis config

manifests/service.pp
Without this change it's possible that we try to start the service and
afterwards modify the debian/ubuntu specifc config file that otherwise
prevents the service from starting.
=> Ubuntu/Debian: Notify service on config changes

README.md, REFERENCE.md, manifests/config.pp, manifests/init.pp, manifests/install.pp, manifests/service.pp, metadata.json, spec/acceptance/ferm_spec.rb, templates/dropin_ferm.conf.epp
This PR add parameter `install_method` that permits to choose between `package` and `vcsrepo`. This permit to install more recent version of `ferm` when desired.
Fixes #103
=> add install_method parameter

README.md, REFERENCE.md, manifests/rule.pp, spec/acceptance/ferm_spec.rb, spec/defines/rule_spec.rb
Implements multiport matching support for the `sport` and `dport` params.
ATTENTION! Breaking change:
Previously `sport` and `dport` allowed the usage of Strings in order to specify multiple ports in the ferm syntax like `(22 80)`.
This commit removes String support for these parameters and enforces strict single `Integer` or `Array[Integer]`.
Thus it is required for users of this module to update their rules in their puppet manifests and/or hiera to switch to real Integer or Integer-Arrays.
=> implement multiport support for dport/sport / drop string support for sport/dport

manifests/rule.pp, spec/defines/rule_spec.rb, spec/type_aliases/actions_spec.rb, spec/type_aliases/policies_spec.rb, spec/type_aliases/port_spec.rb, spec/type_aliases/protocols_spec.rb, spec/type_aliases/tables_spec.rb, types/port.pp
Implement proper port handling with types + validations and fix some regressions and overzealous assumptions.
- use verbose multiport syntax for compatbility with older ferm versions
- implement validations for port ranges
- add test cases for these scenarios
=> implement proper sport/dport types, validate port ranges, fix some minor regressions

metadata.json
current  maintained fedora versions are 32 and newer. they don't support ferm anymore: https://src.fedoraproject.org/rpms/ferm
=> Drop Fedora support (they dont support ferm anymore)

manifests/rule.pp, spec/type_aliases/protocols_spec.rb, types/protocols.pp
'iptables' itself allows protocols to be referenced by numeric values. This patch extends 'Ferm::Protocols' to match integer values between 0 and 255.
> The specified protocol can be one of tcp, udp, udplite, icmp, icmpv6,esp,
> ah, sctp, mh or the special keyword "all", or it can be a numeric value,
> representing one of these protocols or a different one.
source: https://ipset.netfilter.org/iptables.man.html
Also see [0] for Assigned Internet Protocol Numbers.
--
[0] https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml
=> Allow numeric values as protocol references

data/Suse.yaml, metadata.json, spec/classes/ferm_spec.rb
=> Add support for opensuse

metadata.json
=> Drop Arch Linux support

manifests/install.pp
some perl deps can be in a different PATH.
=> Exec: Adjust PATH during ferm installation

manifests/rule.pp, spec/defines/rule_spec.rb, types/negation.pp
I successfully tested negation with 'saddr', 'daddr', 'sport', and 'dport' using ferm v2.6.
The new parameter `negate` takes String as well as Array.
```
'forward_accept_rfc1918':
chain: 'DOCKER-USER'
action: 'ACCEPT'
proto: 'tcp'
saddr:
- '10.0.0.0/8'
negate: 'saddr'
```  
```
'forward_accept_rfc1918':
chain: 'DOCKER-USER'
action: 'ACCEPT'
proto: 'tcp'
saddr:
- '10.0.0.0/8'
negate:
- 'saddr'
```
=> Enable negation of 'saddr', 'daddr', 'sport', and 'dport'

manifests/config.pp, metadata.json
As debian 10 went EOL in June 2024, we should also drop support here
=> Drop Debian 10 support

manifests/config.pp, metadata.json
Drop EL support as ferm has no official package for CentOS 9 (at least to my knowledge). CentOS 7 and 8 are EOL.
=> Drop EL support
